### ISSUE TITLE
kosodate-mapの目的や利用イメージがわかる簡単なドキュメント(100文字程度)

### ISSUE THREAD

**Issue by aca-ta** [Code-for-Funabashi/kosodate-map#16]
叩き台を作成

**Comment by aca-ta** [comment]
ドキュメント案
```
船橋こそだてマップは、地域の子育て環境を調べるための地図です。
- 子どもを保育園に入れたいけど、近所にはどんな保育園があるんだろう
- ○○駅の近くに住みたいけど、どの小学校の学区になるんだろう
- 公園と公民館が近くにある場所はどこだろう

などを簡単に調べることができる地図を作りました。
船橋市が提供しているオープンデータを元に作っています。
今後いろいろなデータを追加していく予定です。
```

**Comment by Jumpo-523** [comment]
データ引用元について（叩き）

---
データreference(仮)
- 保育園一覧: [ふなばしデータカタログ](https://www.city.funabashi.lg.jp/opendata/001/index.html)から抜粋
- 公民館一覧: https://www.city.funabashi.lg.jp/kurashi/gakushu/001/p001031.html

**Comment by aca-ta** [comment]
実施済
http://code4funabashi.org/kosodate-map
