### ISSUE TITLE
NetlifyでSPAのルーティングが解決されるようにする

### ISSUE THREAD

**Issue by aca-ta** [Code-for-Funabashi/kosodate-map#64]
- NetlifyでSPAのルーティングが解決されるようにする。
- Github PagesでSPAのルーティングを解決する実装を削除する
    - https://github.com/Code-for-Funabashi/map/blob/main/public/index.html#L28-L41
    - https://github.com/Code-for-Funabashi/map/blob/main/public/404.html

**Comment by kyoya0819** [comment]
リダイレクトファイルもこのissueで対応した方が良いと個人的には思っています。

```diff
- Github Pages SPAパス解決用のコードを削除する
+ Netlifyへの対応
```

等に変更していただければ当方でまとめて対応させていただきたいと思っています。
